### ISSUE TITLE
Are there any plans to support mysql or postgresql data?

### ISSUE THREAD

**Issue by aaro-n** [productiveops/dokemon#18]
Dokemon should use the sqlite database. Are there any plans to support mysql or postgresql database? If external databases are supported, I can use the data provided by the cloud service provider to view services.
And how does dokemon handle the relative path of the docker-compose volume? I have tested that dokemon must be an absolute path, relative paths are not acceptable, example
```
version: "3.8"
services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    ports:
      - "80:5212"
    volumes:
      - /home/www/cloudreve/uploads:/cloudreve/uploads
      - /home/www/cloudreve/conf.ini:/cloudreve/conf.ini
      - /home/www/cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - /home/www/cloudreve/avatar:/cloudreve/avatar
```
This can find the corresponding volume
```
version: "3.8"
services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    ports:
      - "80:5212"
    volumes:
      - ./cloudreve/uploads:/cloudreve/uploads
      - ./cloudreve/conf.ini:/cloudreve/conf.ini
      - ./cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - ./cloudreve/avatar:/cloudreve/avatar
```
The corresponding folder cannot be found
