### ISSUE TITLE
Unable to access any container!

### ISSUE THREAD

**Issue by abmmhasan** [productiveops/dokemon#36]
` {"level":"error","error":"reading digest latest in docker.io/library/localhost-app: requested access to the resource is denied","containerId":"e5c3f1874750331c924c79fbc2debcfedd4065c1ab43ab1cf7c58f987753b8e4","image":"localhost-app","time":"2024-03-22T14:54:31Z","message":"Error while checking if container is stale"}`

Problem showing with every container.

My docker compose settings:

```yml
  dokemon:
    image: productiveops/dokemon:latest
    container_name: dokemon
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./docker/data/dokemondata:/data
      - /var/run/docker.sock:/var/run/docker.sock
```
