### ISSUE TITLE
env_file location

### ISSUE THREAD

**Issue by D1reW0lf** [productiveops/dokemon#41]
Hi.
When we use the:

```
services:
  myservice:
    env_file:
      - .env
```

Where should we put the .env file?

I tried to put
`/full/path/to/.env`
but it doesn't work, it says `no such file or directory`.
I tried both a full path referring to the host and to the ./data that Dokémon uses. 

(Frankly, having to input the vars one by one on the Variables field it's not the ideal)

Thank you.
